name: pnpm Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  type-check:
    name: Run `pnpm check`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run `pnpm check`
        run: pnpm check
